"""Type stubs for the compiled engine.

The facade is ordinary annotated Python, so this file only has to describe
the extension module underneath it — which is what lets `mypy --strict`
see through `DynamicConfig` to `Database` instead of stopping at `Any`.

Every parameter is named here as well as in the extension's own
docstrings, because these are what an editor completes from: a signature
that reads `(*args, **kwargs)` in a tooltip is a parameter the developer
has to go and look up. The prose for each one is on the compiled method,
which `help()` shows.
"""

from collections.abc import Sequence
from typing import Any, Callable

__version__: str
__engine_version__: str

class Config:
    def __init__(
        self,
        validate: Callable[[Any], Any],
        key: str,
        secrets: Sequence[str] | None,
        fields: Sequence[str],
    ) -> None: ...
    @property
    def key(self) -> str: ...
    @property
    def generation(self) -> int: ...
    # Sources
    def file(self, path: str) -> None: ...
    def discover(self, name: str, paths: Sequence[str]) -> None: ...
    def env(self, prefix: str) -> None: ...
    def nest(self, separator: str) -> None: ...
    def allow_empty_env(self) -> None: ...
    def strict_env(self) -> None: ...
    def whole_document(self) -> None: ...
    def env_file(self, path: str) -> None: ...
    def secrets_dir(self, path: str) -> None: ...
    def profile_env(self, variable: str) -> None: ...
    def cache(self, path: str, mode: str) -> None: ...
    # The remote store
    def remote(self, source: Any) -> None: ...
    def refresh_remote(self) -> None: ...
    def clear_remote(self) -> None: ...
    @property
    def remote_description(self) -> str | None: ...
    # Lifecycle
    def init(self) -> None: ...
    def load(self) -> Any: ...
    def reload(self) -> None: ...
    def current(self) -> Any | None: ...
    def replace(self, model: Any) -> None: ...
    def watch(self, debounce: float, poll_interval: float | None = ...) -> Watch: ...
    def wait_for_change(
        self, seen: int, timeout: float | None = ...
    ) -> tuple[int, Any] | None: ...
    def on_reload(self, hook: Callable[[Any, Any], None]) -> int: ...
    def remove_hook(self, token: int) -> bool: ...
    # Runtime layers
    def set_default(self, path: str, value: Any) -> None: ...
    def set_defaults(self, values: Any) -> None: ...
    def set_override(self, path: str, value: Any) -> None: ...
    def set_assignments(self, assignments: Sequence[str]) -> None: ...
    def clear_defaults(self) -> None: ...
    def clear_overrides(self) -> None: ...
    def clear_assignments(self) -> None: ...
    # `from` and `to` in the extension; `from` is a keyword here, so the
    # stub spells them as what they mean. Both are positional either way.
    def alias(self, old: str, new: str) -> None: ...
    def bind_env(self, path: str, variable: str) -> None: ...
    # Diagnostics
    def source_of(self, path: str) -> tuple[str, str | None] | None: ...
    def is_set(self, path: str) -> bool: ...
    def explain(self, path: str) -> dict[str, Any]: ...
    def check(self) -> dict[str, Any]: ...
    def snapshot(self) -> Snapshot: ...
    def release(self) -> None: ...
    # Telemetry
    def status(self) -> dict[str, Any]: ...
    def remote_status(self) -> dict[str, Any]: ...

def changed_paths(previous: Any, current: Any) -> list[tuple[str, str]]: ...

class Watch:
    @property
    def running(self) -> bool: ...
    def stop(self) -> None: ...
    def detach(self) -> None: ...

class Snapshot:
    def to_dict(self) -> dict[str, Any]: ...
    def source_of(self, path: str) -> tuple[str, str | None] | None: ...
    def contains(self, path: str) -> bool: ...
    def leaf_paths(self) -> list[str]: ...
    def top_level_keys(self) -> list[str]: ...
    def is_empty(self) -> bool: ...
    def diff(self, other: Snapshot) -> list[tuple[str, str]]: ...

class Exposition:
    def __init__(self) -> None: ...
    def add(self, labels: Sequence[tuple[str, str]], config: Config) -> None: ...
    def add_remote(self, labels: Sequence[tuple[str, str]], config: Config) -> None: ...
    def render(self) -> str: ...

class DynamicConfigError(Exception):
    kind: str
    path: str
    origin_kind: str
    origin: str | None

class IoError(DynamicConfigError): ...
class ParseError(DynamicConfigError): ...
class MissingError(DynamicConfigError): ...
class TypeMismatchError(DynamicConfigError): ...
class EnvError(DynamicConfigError): ...

class InvalidError(DynamicConfigError):
    errors: list[dict[str, Any]]

class RemoteError(DynamicConfigError): ...
class AuthError(DynamicConfigError): ...
class DecryptError(DynamicConfigError): ...
class BackendError(DynamicConfigError): ...
